title: Claudio Del Sole
profile_photo: profile_photo.jpg
tagline: Postdoctoral researcher in Statistics
affiliation: University of Milano-Bicocca
location: Milan, Italy
emails: claudio.delsole (at) unimib.it
theme: jekyll-theme-minimal
