title: Claudio Del Sole
profile_photo: profile_photo.jpg
tagline: Postdoctoral researcher in Statistics
university: University of Milano-Bicocca
location: Milan, Italy
department: Department of Economics, Management and Statistics
theme: jekyll-theme-minimal
