title: Claudio Del Sole
profile_photo: profile_photo.jpg
description: Postdoctoral researcher in Statistics
affiliation: University of Milano-Bicocca
location: Milan, Italy
theme: jekyll-theme-minimal
